spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taxRecord?createDatabaseIfNotExist=true #database name
    username: root
    password: #password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
